/**
 * The `kernloop` CLI usage/help text (spec §9). Extracted from cli.ts as plain
 * data so the dispatch shell stays under its line budget; printed verbatim when
 * a command is missing or unknown.
 */
export const USAGE = [
  'usage: kernloop <command> [flags]',
  '  init      [--dir <repo>]                        scaffold .kernloop/',
  '  doctor    [--dir <repo>]                        validate the overlay',
  '  serve     [--dir <repo>]                        MCP server on stdio',
  '  run       --goal G --capability C [--workspace D] [--adapter A] [--plan] [--async] [--id I]',
  '            [--budget tokens=N,usd=N,wallClock=N] [--unlimited]',
  '            --resume RUNID --capability workflow.canonical [--workspace D] [--adapter A]',
  '  status    (--task-id T | --job J)',
  '  brief     --goal G [--id I]',
  '  gate      --gate quality --task-id T --workspace D',
  '            --gate vote --proposal P [--brief-goal G] [--panel 3|7] [--strategy S] [--adapter A] [--task-id T]',
  '            --gate review (--diff D | --diff-file F) [--context C] [--adapter A] [--task-id T]',
  '  recall    --query Q [--limit N]',
  '  remember  --fact F --provenance P [--confidence C]',
  '  distill   --trace <taskId|runId> [--adapter A]   propose a skill from a trace (suggest tier)',
  '  forge     --spec-file <tool-spec.json> [--adapter A]   birth a workshop/* tool in the sandbox',
  '  workshop  run <name> (--input <file> | --input-json <json>)  invoke a born tool in the sandbox',
  '            sweep                                       decay unused tools toward removal',
  '            list                                        live workshop tools + their ladder tier',
  '  manifest  --op list|get|register [--name N] [--version V] [--file J]',
  '  audit     [--op verify|query] [--from N] [--to N] [--type T]',
  '  observe',
  '  metrics   [--out <file>]                         governance metrics in Prometheus exposition format (#125)',
  '  watch     [--task-id T] [--once] [--timeout-ms N]   live-tail the audit chain of a run (#126)',
  '  memory    export [--out <file>]                 portable memory export (JSON; default stdout)',
  '            import <file>                          load a memory export (upserts, audited)',
  '  priors    export [--out <file>]                 routing priors → .kernloop/priors.yaml (YAML)',
  '  models    sync [--ollama-host <H>] [--no-ollama] | list   discover/list the model catalog',
  '  tracker   create --title T --body-file F [--label L]   file an issue (DRY RUN by default)',
  '            close <ref> [--reason R] | comment <ref> --body-file F | label <ref> --add L',
  '            [--execute]   perform the mutation — honored ONLY at the enforce tier (spec §5.5)',
  '  observer  proposals | propose <n> | list           the self-issue loop (spec §5.5)',
  '            file <id> [--execute]   file a proposal via the tracker (DRY RUN by default; enforce-gated)',
  '  program   decompose --goal G --spec F [--parent ID] [--id ID]   decompose a goal into an epic/story tree (preview; spec §5.4)',
  '            author --goal G [--id ID] [--adapter A]   a MODEL proposes the epic/story decomposition (suggest-tier preview; mutates nothing)',
  '            emit (--goal G --spec F [--id ID] | --program ID) [--execute] [--confirm-count N]   file each child as a labeled issue (--program auto-records refs to the ledger; DRY RUN by default; enforce-gated, spam-guarded)',
  '            create --goal G --spec F [--id ID]   persist the decomposed plan to the resumable ledger (.kernloop/programs.sqlite)',
  '            list   the persisted programs in the ledger (id + goal)',
  '            status --program ID   the ledger rollup: planned/emitted/done counts + per-node state',
  '            advance --program ID --node NODE --state emitted|done [--ref URL]   advance one node forward (no daemon; spec §5.4)',
  '            reconcile --program ID [--execute]   reconcile emitted nodes against GitHub: advance emitted → done when the issue is closed (read at any tier; ledger write --execute-gated; #87)',
].join('\n');
